### ISSUE TITLE
Permit to download

### ISSUE THREAD

**Issue by cosmicqbit** [MANMAID007/creative-coding-2-0-in-js-animation-sound-color#1]
Hi I was searching for the downloadable files of this course and found this repo. If you have purchased this course would you mind sharing the access to account temporarily, I will scrap the course and get the files downloaded if you don't mind!. You can have those files as well. In return If you need any Udemy course I can aid you with that. Also I have Bruno Simons Three.js course I can exchange that as well.

**Comment by MANMAID007** [comment]
Sure.

**Comment by cosmicqbit** [comment]
No rush, take your time. Please drop me an email at shariqrazaqadri[at]proton[dot]me when you finish or if you need any course.

**Comment by Adamkaram** [comment]
WOULD ANY ONE SHARE IT WITH ME ALSO

**Comment by cosmicqbit** [comment]
@youktinath Would you mind sharing the login credentials of your account. I will download the files and then you can change the password.
